const ACTION_TYPES = {
  APPOINTMENTS_FILTER_SET_VALUE: "APPOINTMENTS_FILTER_SET_VALUE",
  APPOINTMENTS_DATA_LOAD: "APPOINTMENTS_DATA_LOAD",
  APPOINTMENTS_DATA_LOAD_SUCCEEDED: "APPOINTMENTS_DATA_LOAD_SUCCEEDED",
  APPOINTMENTS_DATA_LOAD_FAILED: "APPOINTMENTS_DATA_LOAD_FAILED",
};

export default ACTION_TYPES;
